### ISSUE TITLE
requirements.txt 依赖了本地盘路径

### ISSUE THREAD

**Issue by tiny1990** [Renkai/epub_juicer#1]
如题，希望改造下依赖 能一键run

**Comment by Renkai** [comment]
蛤? 我也不知道为什么会这样, 大部分依赖应该只是装主要依赖的时候跟着被带进来的, 估计去掉也没问题. 我去掉了, 可以再试试

**Comment by tiny1990** [comment]
> 蛤? 我也不知道为什么会这样, 大部分依赖应该只是装主要依赖的时候跟着被带进来的, 估计去掉也没问题. 我去掉了, 可以再试试

感谢大佬的分享，受益匪浅  基于大佬视频和项目的思路自己搞了下，
加了 actions，自动添加生词本中，希望自己能坚持提升英文能力
